apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-amit
  labels:
    app: demo-app-amit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-amit
  template:
    metadata:
      labels:
        app: demo-app-amit
    spec:
      containers:
        - name: demo-app-amit
          image: amitjoshi007/frontend-app:b79ddccbbd0834aed036e3a7737a635a996992ae
          ports:
            - containerPort: 4200
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: demo-amit-service
spec:
  type: LoadBalancer
  selector:
    app: demo-app-amit
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200