### BACKEND TIER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-amit
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend-amit
  template:
    metadata:
      labels:
        app: backend-amit
    spec:
      containers:
        - name: backend-container
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.backend.datasourceUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.database.user | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.database.password | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-app
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: backend-amit
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-metrics-internal
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend-amit
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}