# Change server port to 8087
server.port=8087

# The host 'postgres-db' matches the service name in your docker-compose.yml
spring.datasource.url=jdbc:postgresql://postgres-db:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver


# Tells Hibernate to use PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically creates/updates tables based on your Java @Entity classes
spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true


# Show SQL queries in the console logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

