# Change server port to 8087
server.port=8087

# The host 'postgres-db' matches the service name in your docker-compose.yml
spring.datasource.url=jdbc:postgresql://postgres-db:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Tells Hibernate to use PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CRUCIAL CHANGE 1: Change 'update' to 'create-drop' or 'update'
# 'create-drop' will clean out the database schema fresh on every restart
# so you don't keep old null-column tables around.
spring.jpa.hibernate.ddl-auto=create-drop

# CRUCIAL CHANGE 2: TURN THIS TO FALSE (or remove it)
# Since you don't want or need the automatic INSERT script anymore,
# turning this to false prevents Spring Boot from looking for a data.sql file.
spring.jpa.defer-datasource-initialization=false

# Show SQL queries in the console logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,prometheus