# This is a basic workflow to help you get started with Actions

name: folderNFiles

# Controls when the workflow will run
on:
  push:
    branches: [ "master"]
    paths:
      - 'demo/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'demo/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Step 1: Create a folder in C drive
      - name: Create initial folder in C drive
        run: mkdir C:\FirstFolderNew
        continue-on-error: true # Prevents the workflow from breaking if the folder already exists

      # Step 2: Create a file inside the first folder
      - name: Create file1 inside FirstFolder
        run: echo This is file 1 > C:\FirstFolder\file1.txt

      # Step 3: Create another folder (nested inside or standalone, here created standalone in C)
      - name: Create second folder in C drive
        run: mkdir C:\SecondFolder
        continue-on-error: true

      # Step 4: Create file2 inside the new folder
      - name: Create file2 inside SecondFolderNew
        run: echo This is file 2 > C:\SecondFolder\file2.txt
